// Generated by the gigasGenerator.  ONLY CAN TODO 'handleMessage' Method!

package org.gigas.chat.handler;

import org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo;
import org.gigas.core.server.handler.IHandler;

import com.google.protobuf.MessageLite;

public class ChatInfoHandler extends IHandler {

	@Override
	public void handleMessage(MessageLite message) {
		ChatInfo msg = (ChatInfo) message;
		// TODO
	}
}