// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package org.gigas.chat.message.proto;

public final class ChatMessageFactory {
	private ChatMessageFactory() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public interface ChatInfoOrBuilder extends com.google.protobuf.MessageLiteOrBuilder {

		// optional string content = 1;
		/**
		 * <code>optional string content = 1;</code>
		 * 
		 * <pre>
		 * 聊天内容
		 * </pre>
		 */
		boolean hasContent();

		/**
		 * <code>optional string content = 1;</code>
		 * 
		 * <pre>
		 * 聊天内容
		 * </pre>
		 */
		java.lang.String getContent();

		/**
		 * <code>optional string content = 1;</code>
		 * 
		 * <pre>
		 * 聊天内容
		 * </pre>
		 */
		com.google.protobuf.ByteString getContentBytes();

		// optional int64 number = 2;
		/**
		 * <code>optional int64 number = 2;</code>
		 * 
		 * <pre>
		 * 发送者编号
		 * </pre>
		 */
		boolean hasNumber();

		/**
		 * <code>optional int64 number = 2;</code>
		 * 
		 * <pre>
		 * 发送者编号
		 * </pre>
		 */
		long getNumber();

		// repeated int32 integerList = 3;
		/**
		 * <code>repeated int32 integerList = 3;</code>
		 * 
		 * <pre>
		 * 整型数组
		 * </pre>
		 */
		java.util.List<java.lang.Integer> getIntegerListList();

		/**
		 * <code>repeated int32 integerList = 3;</code>
		 * 
		 * <pre>
		 * 整型数组
		 * </pre>
		 */
		int getIntegerListCount();

		/**
		 * <code>repeated int32 integerList = 3;</code>
		 * 
		 * <pre>
		 * 整型数组
		 * </pre>
		 */
		int getIntegerList(int index);

		// optional .RoleChatInfo roleChatInfo = 4;
		/**
		 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
		 * 
		 * <pre>
		 * roleChatInfo
		 * </pre>
		 */
		boolean hasRoleChatInfo();

		/**
		 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
		 * 
		 * <pre>
		 * roleChatInfo
		 * </pre>
		 */
		org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo getRoleChatInfo();
	}

	/**
	 * Protobuf type {@code ChatInfo}
	 * 
	 * <pre>
	 * 聊天消息
	 * </pre>
	 */
	public static final class ChatInfo extends com.google.protobuf.GeneratedMessageLite implements ChatInfoOrBuilder {
		// Use ChatInfo.newBuilder() to construct.
		private ChatInfo(com.google.protobuf.GeneratedMessageLite.Builder builder) {
			super(builder);

		}

		private ChatInfo(boolean noInit) {
		}

		private static final ChatInfo defaultInstance;

		public static ChatInfo getDefaultInstance() {
			return defaultInstance;
		}

		public ChatInfo getDefaultInstanceForType() {
			return defaultInstance;
		}

		private ChatInfo(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						content_ = input.readBytes();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						number_ = input.readInt64();
						break;
					}
					case 24: {
						if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
							integerList_ = new java.util.ArrayList<java.lang.Integer>();
							mutable_bitField0_ |= 0x00000004;
						}
						integerList_.add(input.readInt32());
						break;
					}
					case 26: {
						int length = input.readRawVarint32();
						int limit = input.pushLimit(length);
						if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
							integerList_ = new java.util.ArrayList<java.lang.Integer>();
							mutable_bitField0_ |= 0x00000004;
						}
						while (input.getBytesUntilLimit() > 0) {
							integerList_.add(input.readInt32());
						}
						input.popLimit(limit);
						break;
					}
					case 34: {
						org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.Builder subBuilder = null;
						if (((bitField0_ & 0x00000004) == 0x00000004)) {
							subBuilder = roleChatInfo_.toBuilder();
						}
						roleChatInfo_ = input.readMessage(org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.PARSER, extensionRegistry);
						if (subBuilder != null) {
							subBuilder.mergeFrom(roleChatInfo_);
							roleChatInfo_ = subBuilder.buildPartial();
						}
						bitField0_ |= 0x00000004;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
					integerList_ = java.util.Collections.unmodifiableList(integerList_);
				}
				makeExtensionsImmutable();
			}
		}

		public static com.google.protobuf.Parser<ChatInfo> PARSER = new com.google.protobuf.AbstractParser<ChatInfo>() {
			public ChatInfo parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return new ChatInfo(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<ChatInfo> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// optional string content = 1;
		public static final int CONTENT_FIELD_NUMBER = 1;
		private java.lang.Object content_;

		/**
		 * <code>optional string content = 1;</code>
		 * 
		 * <pre>
		 * 聊天内容
		 * </pre>
		 */
		public boolean hasContent() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>optional string content = 1;</code>
		 * 
		 * <pre>
		 * 聊天内容
		 * </pre>
		 */
		public java.lang.String getContent() {
			java.lang.Object ref = content_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					content_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string content = 1;</code>
		 * 
		 * <pre>
		 * 聊天内容
		 * </pre>
		 */
		public com.google.protobuf.ByteString getContentBytes() {
			java.lang.Object ref = content_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				content_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional int64 number = 2;
		public static final int NUMBER_FIELD_NUMBER = 2;
		private long number_;

		/**
		 * <code>optional int64 number = 2;</code>
		 * 
		 * <pre>
		 * 发送者编号
		 * </pre>
		 */
		public boolean hasNumber() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional int64 number = 2;</code>
		 * 
		 * <pre>
		 * 发送者编号
		 * </pre>
		 */
		public long getNumber() {
			return number_;
		}

		// repeated int32 integerList = 3;
		public static final int INTEGERLIST_FIELD_NUMBER = 3;
		private java.util.List<java.lang.Integer> integerList_;

		/**
		 * <code>repeated int32 integerList = 3;</code>
		 * 
		 * <pre>
		 * 整型数组
		 * </pre>
		 */
		public java.util.List<java.lang.Integer> getIntegerListList() {
			return integerList_;
		}

		/**
		 * <code>repeated int32 integerList = 3;</code>
		 * 
		 * <pre>
		 * 整型数组
		 * </pre>
		 */
		public int getIntegerListCount() {
			return integerList_.size();
		}

		/**
		 * <code>repeated int32 integerList = 3;</code>
		 * 
		 * <pre>
		 * 整型数组
		 * </pre>
		 */
		public int getIntegerList(int index) {
			return integerList_.get(index);
		}

		// optional .RoleChatInfo roleChatInfo = 4;
		public static final int ROLECHATINFO_FIELD_NUMBER = 4;
		private org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo roleChatInfo_;

		/**
		 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
		 * 
		 * <pre>
		 * roleChatInfo
		 * </pre>
		 */
		public boolean hasRoleChatInfo() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
		 * 
		 * <pre>
		 * roleChatInfo
		 * </pre>
		 */
		public org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo getRoleChatInfo() {
			return roleChatInfo_;
		}

		private void initFields() {
			content_ = "";
			number_ = 0L;
			integerList_ = java.util.Collections.emptyList();
			roleChatInfo_ = org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.getDefaultInstance();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getContentBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt64(2, number_);
			}
			for (int i = 0; i < integerList_.size(); i++) {
				output.writeInt32(3, integerList_.get(i));
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeMessage(4, roleChatInfo_);
			}
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getContentBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, number_);
			}
			{
				int dataSize = 0;
				for (int i = 0; i < integerList_.size(); i++) {
					dataSize += com.google.protobuf.CodedOutputStream.computeInt32SizeNoTag(integerList_.get(i));
				}
				size += dataSize;
				size += 1 * getIntegerListList().size();
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, roleChatInfo_);
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		/**
		 * Protobuf type {@code ChatInfo}
		 * 
		 * <pre>
		 * 聊天消息
		 * </pre>
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageLite.Builder<org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo, Builder> implements org.gigas.chat.message.proto.ChatMessageFactory.ChatInfoOrBuilder {
			// Construct using
			// org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				content_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				number_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000002);
				integerList_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000004);
				roleChatInfo_ = org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.getDefaultInstance();
				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo getDefaultInstanceForType() {
				return org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo.getDefaultInstance();
			}

			public org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo build() {
				org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo buildPartial() {
				org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo result = new org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.content_ = content_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.number_ = number_;
				if (((bitField0_ & 0x00000004) == 0x00000004)) {
					integerList_ = java.util.Collections.unmodifiableList(integerList_);
					bitField0_ = (bitField0_ & ~0x00000004);
				}
				result.integerList_ = integerList_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000004;
				}
				result.roleChatInfo_ = roleChatInfo_;
				result.bitField0_ = to_bitField0_;
				return result;
			}

			public Builder mergeFrom(org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo other) {
				if (other == org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo.getDefaultInstance())
					return this;
				if (other.hasContent()) {
					bitField0_ |= 0x00000001;
					content_ = other.content_;

				}
				if (other.hasNumber()) {
					setNumber(other.getNumber());
				}
				if (!other.integerList_.isEmpty()) {
					if (integerList_.isEmpty()) {
						integerList_ = other.integerList_;
						bitField0_ = (bitField0_ & ~0x00000004);
					} else {
						ensureIntegerListIsMutable();
						integerList_.addAll(other.integerList_);
					}

				}
				if (other.hasRoleChatInfo()) {
					mergeRoleChatInfo(other.getRoleChatInfo());
				}
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// optional string content = 1;
			private java.lang.Object content_ = "";

			/**
			 * <code>optional string content = 1;</code>
			 * 
			 * <pre>
			 * 聊天内容
			 * </pre>
			 */
			public boolean hasContent() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>optional string content = 1;</code>
			 * 
			 * <pre>
			 * 聊天内容
			 * </pre>
			 */
			public java.lang.String getContent() {
				java.lang.Object ref = content_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					content_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string content = 1;</code>
			 * 
			 * <pre>
			 * 聊天内容
			 * </pre>
			 */
			public com.google.protobuf.ByteString getContentBytes() {
				java.lang.Object ref = content_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
					content_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string content = 1;</code>
			 * 
			 * <pre>
			 * 聊天内容
			 * </pre>
			 */
			public Builder setContent(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				content_ = value;

				return this;
			}

			/**
			 * <code>optional string content = 1;</code>
			 * 
			 * <pre>
			 * 聊天内容
			 * </pre>
			 */
			public Builder clearContent() {
				bitField0_ = (bitField0_ & ~0x00000001);
				content_ = getDefaultInstance().getContent();

				return this;
			}

			/**
			 * <code>optional string content = 1;</code>
			 * 
			 * <pre>
			 * 聊天内容
			 * </pre>
			 */
			public Builder setContentBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				content_ = value;

				return this;
			}

			// optional int64 number = 2;
			private long number_;

			/**
			 * <code>optional int64 number = 2;</code>
			 * 
			 * <pre>
			 * 发送者编号
			 * </pre>
			 */
			public boolean hasNumber() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional int64 number = 2;</code>
			 * 
			 * <pre>
			 * 发送者编号
			 * </pre>
			 */
			public long getNumber() {
				return number_;
			}

			/**
			 * <code>optional int64 number = 2;</code>
			 * 
			 * <pre>
			 * 发送者编号
			 * </pre>
			 */
			public Builder setNumber(long value) {
				bitField0_ |= 0x00000002;
				number_ = value;

				return this;
			}

			/**
			 * <code>optional int64 number = 2;</code>
			 * 
			 * <pre>
			 * 发送者编号
			 * </pre>
			 */
			public Builder clearNumber() {
				bitField0_ = (bitField0_ & ~0x00000002);
				number_ = 0L;

				return this;
			}

			// repeated int32 integerList = 3;
			private java.util.List<java.lang.Integer> integerList_ = java.util.Collections.emptyList();

			private void ensureIntegerListIsMutable() {
				if (!((bitField0_ & 0x00000004) == 0x00000004)) {
					integerList_ = new java.util.ArrayList<java.lang.Integer>(integerList_);
					bitField0_ |= 0x00000004;
				}
			}

			/**
			 * <code>repeated int32 integerList = 3;</code>
			 * 
			 * <pre>
			 * 整型数组
			 * </pre>
			 */
			public java.util.List<java.lang.Integer> getIntegerListList() {
				return java.util.Collections.unmodifiableList(integerList_);
			}

			/**
			 * <code>repeated int32 integerList = 3;</code>
			 * 
			 * <pre>
			 * 整型数组
			 * </pre>
			 */
			public int getIntegerListCount() {
				return integerList_.size();
			}

			/**
			 * <code>repeated int32 integerList = 3;</code>
			 * 
			 * <pre>
			 * 整型数组
			 * </pre>
			 */
			public int getIntegerList(int index) {
				return integerList_.get(index);
			}

			/**
			 * <code>repeated int32 integerList = 3;</code>
			 * 
			 * <pre>
			 * 整型数组
			 * </pre>
			 */
			public Builder setIntegerList(int index, int value) {
				ensureIntegerListIsMutable();
				integerList_.set(index, value);

				return this;
			}

			/**
			 * <code>repeated int32 integerList = 3;</code>
			 * 
			 * <pre>
			 * 整型数组
			 * </pre>
			 */
			public Builder addIntegerList(int value) {
				ensureIntegerListIsMutable();
				integerList_.add(value);

				return this;
			}

			/**
			 * <code>repeated int32 integerList = 3;</code>
			 * 
			 * <pre>
			 * 整型数组
			 * </pre>
			 */
			public Builder addAllIntegerList(java.lang.Iterable<? extends java.lang.Integer> values) {
				ensureIntegerListIsMutable();
				super.addAll(values, integerList_);

				return this;
			}

			/**
			 * <code>repeated int32 integerList = 3;</code>
			 * 
			 * <pre>
			 * 整型数组
			 * </pre>
			 */
			public Builder clearIntegerList() {
				integerList_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000004);

				return this;
			}

			// optional .RoleChatInfo roleChatInfo = 4;
			private org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo roleChatInfo_ = org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.getDefaultInstance();

			/**
			 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
			 * 
			 * <pre>
			 * roleChatInfo
			 * </pre>
			 */
			public boolean hasRoleChatInfo() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
			 * 
			 * <pre>
			 * roleChatInfo
			 * </pre>
			 */
			public org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo getRoleChatInfo() {
				return roleChatInfo_;
			}

			/**
			 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
			 * 
			 * <pre>
			 * roleChatInfo
			 * </pre>
			 */
			public Builder setRoleChatInfo(org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo value) {
				if (value == null) {
					throw new NullPointerException();
				}
				roleChatInfo_ = value;

				bitField0_ |= 0x00000008;
				return this;
			}

			/**
			 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
			 * 
			 * <pre>
			 * roleChatInfo
			 * </pre>
			 */
			public Builder setRoleChatInfo(org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.Builder builderForValue) {
				roleChatInfo_ = builderForValue.build();

				bitField0_ |= 0x00000008;
				return this;
			}

			/**
			 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
			 * 
			 * <pre>
			 * roleChatInfo
			 * </pre>
			 */
			public Builder mergeRoleChatInfo(org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo value) {
				if (((bitField0_ & 0x00000008) == 0x00000008) && roleChatInfo_ != org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.getDefaultInstance()) {
					roleChatInfo_ = org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.newBuilder(roleChatInfo_).mergeFrom(value).buildPartial();
				} else {
					roleChatInfo_ = value;
				}

				bitField0_ |= 0x00000008;
				return this;
			}

			/**
			 * <code>optional .RoleChatInfo roleChatInfo = 4;</code>
			 * 
			 * <pre>
			 * roleChatInfo
			 * </pre>
			 */
			public Builder clearRoleChatInfo() {
				roleChatInfo_ = org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.getDefaultInstance();

				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			// @@protoc_insertion_point(builder_scope:ChatInfo)
		}

		static {
			defaultInstance = new ChatInfo(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:ChatInfo)
	}

	public interface RoleChatInfoOrBuilder extends com.google.protobuf.MessageLiteOrBuilder {

		// optional int64 roleId = 1;
		/**
		 * <code>optional int64 roleId = 1;</code>
		 * 
		 * <pre>
		 * 角色ID
		 * </pre>
		 */
		boolean hasRoleId();

		/**
		 * <code>optional int64 roleId = 1;</code>
		 * 
		 * <pre>
		 * 角色ID
		 * </pre>
		 */
		long getRoleId();

		// optional string name = 2;
		/**
		 * <code>optional string name = 2;</code>
		 * 
		 * <pre>
		 * 角色名
		 * </pre>
		 */
		boolean hasName();

		/**
		 * <code>optional string name = 2;</code>
		 * 
		 * <pre>
		 * 角色名
		 * </pre>
		 */
		java.lang.String getName();

		/**
		 * <code>optional string name = 2;</code>
		 * 
		 * <pre>
		 * 角色名
		 * </pre>
		 */
		com.google.protobuf.ByteString getNameBytes();

		// optional int32 level = 3;
		/**
		 * <code>optional int32 level = 3;</code>
		 * 
		 * <pre>
		 * 等级
		 * </pre>
		 */
		boolean hasLevel();

		/**
		 * <code>optional int32 level = 3;</code>
		 * 
		 * <pre>
		 * 等级
		 * </pre>
		 */
		int getLevel();

		// optional bool sex = 4;
		/**
		 * <code>optional bool sex = 4;</code>
		 * 
		 * <pre>
		 * 性别
		 * </pre>
		 */
		boolean hasSex();

		/**
		 * <code>optional bool sex = 4;</code>
		 * 
		 * <pre>
		 * 性别
		 * </pre>
		 */
		boolean getSex();
	}

	/**
	 * Protobuf type {@code RoleChatInfo}
	 * 
	 * <pre>
	 * 玩家简要信息
	 * </pre>
	 */
	public static final class RoleChatInfo extends com.google.protobuf.GeneratedMessageLite implements RoleChatInfoOrBuilder {
		// Use RoleChatInfo.newBuilder() to construct.
		private RoleChatInfo(com.google.protobuf.GeneratedMessageLite.Builder builder) {
			super(builder);

		}

		private RoleChatInfo(boolean noInit) {
		}

		private static final RoleChatInfo defaultInstance;

		public static RoleChatInfo getDefaultInstance() {
			return defaultInstance;
		}

		public RoleChatInfo getDefaultInstanceForType() {
			return defaultInstance;
		}

		private RoleChatInfo(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						roleId_ = input.readInt64();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						name_ = input.readBytes();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						level_ = input.readInt32();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000008;
						sex_ = input.readBool();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				makeExtensionsImmutable();
			}
		}

		public static com.google.protobuf.Parser<RoleChatInfo> PARSER = new com.google.protobuf.AbstractParser<RoleChatInfo>() {
			public RoleChatInfo parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return new RoleChatInfo(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<RoleChatInfo> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// optional int64 roleId = 1;
		public static final int ROLEID_FIELD_NUMBER = 1;
		private long roleId_;

		/**
		 * <code>optional int64 roleId = 1;</code>
		 * 
		 * <pre>
		 * 角色ID
		 * </pre>
		 */
		public boolean hasRoleId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>optional int64 roleId = 1;</code>
		 * 
		 * <pre>
		 * 角色ID
		 * </pre>
		 */
		public long getRoleId() {
			return roleId_;
		}

		// optional string name = 2;
		public static final int NAME_FIELD_NUMBER = 2;
		private java.lang.Object name_;

		/**
		 * <code>optional string name = 2;</code>
		 * 
		 * <pre>
		 * 角色名
		 * </pre>
		 */
		public boolean hasName() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional string name = 2;</code>
		 * 
		 * <pre>
		 * 角色名
		 * </pre>
		 */
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					name_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string name = 2;</code>
		 * 
		 * <pre>
		 * 角色名
		 * </pre>
		 */
		public com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional int32 level = 3;
		public static final int LEVEL_FIELD_NUMBER = 3;
		private int level_;

		/**
		 * <code>optional int32 level = 3;</code>
		 * 
		 * <pre>
		 * 等级
		 * </pre>
		 */
		public boolean hasLevel() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>optional int32 level = 3;</code>
		 * 
		 * <pre>
		 * 等级
		 * </pre>
		 */
		public int getLevel() {
			return level_;
		}

		// optional bool sex = 4;
		public static final int SEX_FIELD_NUMBER = 4;
		private boolean sex_;

		/**
		 * <code>optional bool sex = 4;</code>
		 * 
		 * <pre>
		 * 性别
		 * </pre>
		 */
		public boolean hasSex() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		/**
		 * <code>optional bool sex = 4;</code>
		 * 
		 * <pre>
		 * 性别
		 * </pre>
		 */
		public boolean getSex() {
			return sex_;
		}

		private void initFields() {
			roleId_ = 0L;
			name_ = "";
			level_ = 0;
			sex_ = false;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, roleId_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getNameBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, level_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBool(4, sex_);
			}
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, roleId_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getNameBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, level_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeBoolSize(4, sex_);
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		/**
		 * Protobuf type {@code RoleChatInfo}
		 * 
		 * <pre>
		 * 玩家简要信息
		 * </pre>
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageLite.Builder<org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo, Builder> implements org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfoOrBuilder {
			// Construct using
			// org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				roleId_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				name_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				level_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				sex_ = false;
				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo getDefaultInstanceForType() {
				return org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.getDefaultInstance();
			}

			public org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo build() {
				org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo buildPartial() {
				org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo result = new org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.roleId_ = roleId_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.name_ = name_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.level_ = level_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.sex_ = sex_;
				result.bitField0_ = to_bitField0_;
				return result;
			}

			public Builder mergeFrom(org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo other) {
				if (other == org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo.getDefaultInstance())
					return this;
				if (other.hasRoleId()) {
					setRoleId(other.getRoleId());
				}
				if (other.hasName()) {
					bitField0_ |= 0x00000002;
					name_ = other.name_;

				}
				if (other.hasLevel()) {
					setLevel(other.getLevel());
				}
				if (other.hasSex()) {
					setSex(other.getSex());
				}
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (org.gigas.chat.message.proto.ChatMessageFactory.RoleChatInfo) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// optional int64 roleId = 1;
			private long roleId_;

			/**
			 * <code>optional int64 roleId = 1;</code>
			 * 
			 * <pre>
			 * 角色ID
			 * </pre>
			 */
			public boolean hasRoleId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>optional int64 roleId = 1;</code>
			 * 
			 * <pre>
			 * 角色ID
			 * </pre>
			 */
			public long getRoleId() {
				return roleId_;
			}

			/**
			 * <code>optional int64 roleId = 1;</code>
			 * 
			 * <pre>
			 * 角色ID
			 * </pre>
			 */
			public Builder setRoleId(long value) {
				bitField0_ |= 0x00000001;
				roleId_ = value;

				return this;
			}

			/**
			 * <code>optional int64 roleId = 1;</code>
			 * 
			 * <pre>
			 * 角色ID
			 * </pre>
			 */
			public Builder clearRoleId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				roleId_ = 0L;

				return this;
			}

			// optional string name = 2;
			private java.lang.Object name_ = "";

			/**
			 * <code>optional string name = 2;</code>
			 * 
			 * <pre>
			 * 角色名
			 * </pre>
			 */
			public boolean hasName() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional string name = 2;</code>
			 * 
			 * <pre>
			 * 角色名
			 * </pre>
			 */
			public java.lang.String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string name = 2;</code>
			 * 
			 * <pre>
			 * 角色名
			 * </pre>
			 */
			public com.google.protobuf.ByteString getNameBytes() {
				java.lang.Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string name = 2;</code>
			 * 
			 * <pre>
			 * 角色名
			 * </pre>
			 */
			public Builder setName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				name_ = value;

				return this;
			}

			/**
			 * <code>optional string name = 2;</code>
			 * 
			 * <pre>
			 * 角色名
			 * </pre>
			 */
			public Builder clearName() {
				bitField0_ = (bitField0_ & ~0x00000002);
				name_ = getDefaultInstance().getName();

				return this;
			}

			/**
			 * <code>optional string name = 2;</code>
			 * 
			 * <pre>
			 * 角色名
			 * </pre>
			 */
			public Builder setNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				name_ = value;

				return this;
			}

			// optional int32 level = 3;
			private int level_;

			/**
			 * <code>optional int32 level = 3;</code>
			 * 
			 * <pre>
			 * 等级
			 * </pre>
			 */
			public boolean hasLevel() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional int32 level = 3;</code>
			 * 
			 * <pre>
			 * 等级
			 * </pre>
			 */
			public int getLevel() {
				return level_;
			}

			/**
			 * <code>optional int32 level = 3;</code>
			 * 
			 * <pre>
			 * 等级
			 * </pre>
			 */
			public Builder setLevel(int value) {
				bitField0_ |= 0x00000004;
				level_ = value;

				return this;
			}

			/**
			 * <code>optional int32 level = 3;</code>
			 * 
			 * <pre>
			 * 等级
			 * </pre>
			 */
			public Builder clearLevel() {
				bitField0_ = (bitField0_ & ~0x00000004);
				level_ = 0;

				return this;
			}

			// optional bool sex = 4;
			private boolean sex_;

			/**
			 * <code>optional bool sex = 4;</code>
			 * 
			 * <pre>
			 * 性别
			 * </pre>
			 */
			public boolean hasSex() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>optional bool sex = 4;</code>
			 * 
			 * <pre>
			 * 性别
			 * </pre>
			 */
			public boolean getSex() {
				return sex_;
			}

			/**
			 * <code>optional bool sex = 4;</code>
			 * 
			 * <pre>
			 * 性别
			 * </pre>
			 */
			public Builder setSex(boolean value) {
				bitField0_ |= 0x00000008;
				sex_ = value;

				return this;
			}

			/**
			 * <code>optional bool sex = 4;</code>
			 * 
			 * <pre>
			 * 性别
			 * </pre>
			 */
			public Builder clearSex() {
				bitField0_ = (bitField0_ & ~0x00000008);
				sex_ = false;

				return this;
			}

			// @@protoc_insertion_point(builder_scope:RoleChatInfo)
		}

		static {
			defaultInstance = new RoleChatInfo(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:RoleChatInfo)
	}

	static {
	}

	// @@protoc_insertion_point(outer_class_scope)
}
