// Generated by the gigasGenerator.  DO NOT EDIT!

package org.gigas.chat.message;

import org.gigas.chat.message.proto.ChatMessageFactory;
import org.gigas.chat.message.proto.ChatMessageFactory.ChatInfo.Builder;
import org.gigas.core.server.message.ProtoBufPackage;

import com.google.protobuf.GeneratedMessageLite;


public class ChatInfoMessageBuilder extends ProtoBufPackage {

	private String content;// 聊天内容

	private long number;// 发送者编号

	/**
	 *聊天内容setter
	 */
	public void setContent(String content){ 
		this.content=content;
	}

	/**
	 *聊天内容getter
	 */
	public String getContent() {
		return this.content;
	}
	/**
	 *发送者编号setter
	 */
	public void setNumber(long number){ 
		this.number=number;
	}

	/**
	 *发送者编号getter
	 */
	public long getNumber() {
		return this.number;
	}

	public ChatMessageFactory.ChatInfo build() {
		Builder builder = ChatMessageFactory.ChatInfo.newBuilder();
		builder.setContent(this.content);
		builder.setNumber(this.number);
		return builder.build();
	}

	@Override
	public long getId() {
		return 1001;
	}

	@Override
	public Class<? extends GeneratedMessageLite> getClazz() {
		return ChatMessageFactory.ChatInfo.class;
	}
	

}